export default defineAppConfig({
  pages: [
    "pages/learn/index",
    "pages/session/index",
    "pages/review/index",
    "pages/review-session/index",
    "pages/library/index",
    "pages/my/index",
    "pages/membership/index",
    "pages/login/index",
    "pages/goal/index",
    "pages/wrongbook/index",
    "pages/favorites/index",
    "pages/legal/index",
    "pages/orbit/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#F7F8FA",
    navigationBarTitleText: "沃天澜",
    navigationBarTextStyle: "black",
    backgroundColor: "#F7F8FA",
  },
  tabBar: {
    color: "#66707E",
    selectedColor: "#C62828",
    backgroundColor: "#FFFFFF",
    borderStyle: "white",
    list: [
      { pagePath: "pages/learn/index", text: "学习" },
      { pagePath: "pages/review/index", text: "复习" },
      { pagePath: "pages/library/index", text: "词库" },
      { pagePath: "pages/my/index", text: "我的" },
    ],
  },
});
